### ISSUE TITLE
[SFC\SNES] Black screen is displaying but sound is playing

### ISSUE THREAD

**Issue by randomsomeone69** [ares-emulator/ares#650] opened 2022-07-27 12:36 UTC
When I start Super Mario Kart, the screen is black but the sound is playing. This is annoying because without graphis, it's hard (nearly impossible) to play the game. This is random also. 

Here's the path to the roms that I've discovered the bug:

J:\Gigaleak\other\NEWS\テープリストア\NEWS_05\home\kimura\util\mkart.rom (0% sucessful displaying graphics)
J:\Rom\SNES\Super Mario Kart (Japan).sfc (had happened once)
J:\Gigaleak\other\NEWS\テープリストア\NEWS_05\home\kimura\kart\risc\mak\kart.rom
J:\Gigaleak\other\NEWS\テープリストア\NEWS_05\home\kimura\kart\mak\mario-kart.bin

I will update the games with path when I discover that bug again on other files.

**Comment by remutro** [comment] 2022-07-27 15:53
I can't comment on the roms from the Gigaleak. In general we focus on licensed, released games that match No-Intro's database. The correct Japanese Super Mario Kart rom works without issue. Have you tried using the latest available nightly build (there was an issue with the background 4 layer that was just fixed)? What version of ares were you using? What OS? What drivers do you have selected in ares? 

I've reset and loaded/unloaded many times. Works every time for me:
![image](https://user-images.githubusercontent.com/84990500/181292663-11aad94c-ad6c-4421-b297-694975771ad2.png)

**Comment by LukeUsher** [comment] 2022-07-28 08:16
Closing as invalid: we can't reproduce this using any legitimately dumped roms, and we can't support or endorse the use of leaked content.

**Closed by LukeUsher** 2022-07-28 08:16 UTC
