### ISSUE TITLE
[N64] BattleTanx (U): doesn't boot/black screen

### ISSUE THREAD

**Issue by AbreuEfechou** [ares-emulator/ares#61] opened 2021-08-17 05:27 UTC
Version: latest
ROM CRC-32: 6C230765 (No-intro)

**Comment by bigbass1997** [comment] 2021-08-17 06:14
Once you load the ROM, go to the top menu, under Nintendo 64, click Reset. Wait a moment, and then it should work. It's a known issue.

Previously discussed on Discord, it has something to do with the reset state of the emulator. While there is a one bit difference on soft reset (or NMI), in PIF RAM at bootup, this is emulated already here: https://github.com/higan-emu/ares/blob/d653ca8f22a2dd029f54f9733e17599feb91d287/ares/n64/pi/pi.cpp#L43-L58

I suspect it might be something unrelated to the PIF RAM state at cold-boot/reset, as that does appear to be console accurate. But it's impossible to tell what the real root cause is without a thorough investigation into what the game gets hung up on, on cold boot, rather than a reset.

**Comment by remutro** [comment] 2021-08-17 13:42
The same issue impacts  Battletanx: Global Assault, but only the USA ROM. Curiously, the EU Battletanx: Global Assult ROM does not experience this issue. As bigbass1997 already pointed out, you can work around this issue for both USA ROMs by resetting these games after loading.

**Comment by remutro** [comment] 2021-09-02 18:28
Both games should now boot on first try now and can be played as of pull request: https://github.com/higan-emu/ares/pull/153

Can you close this issue please?

**Closed as completed** 2021-09-09 15:53 UTC
Labels: bug
